In [1]:
import torch
import numpy as np

In [3]:
data = [[1, 2], [3, 4]]

In [4]:
data

[[1, 2], [3, 4]]

In [5]:
x_data = torch.tensor(data)

In [6]:
x_data

tensor([[1, 2],
        [3, 4]])

In [7]:
nparray = np.array(data)
nparray

array([[1, 2],
       [3, 4]])

In [8]:
torch.cuda.is_available()

False

In [9]:
a = torch.ones(2, 3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
b = torch.rand((3, 2))
b

tensor([[0.2442, 0.2705],
        [0.7714, 0.3629],
        [0.7151, 0.4094]])

In [16]:
b.device

device(type='cpu')

In [17]:
b.dtype

torch.float32

In [18]:
b.shape

torch.Size([3, 2])

In [19]:
# 多个模型头的输出拼接
feature1 = torch.randn(10, 64)  # 10个样本，64维特征
feature2 = torch.randn(10, 32)
feature3 = torch.randn(10, 16)

# 拼接成 112 维特征向量
combined = torch.cat([feature1, feature2, feature3], dim=1)  # 形状: (10, 112)